"""Data-access contract for the research service.

Services only talk to this interface. Today `MockResearchRepository` serves
`app/mock/mock_data.json`; a database-backed repository can replace it later by
implementing the same methods and being returned from `app.deps.get_repository`.

Methods return plain dicts (or None / [] when nothing matches). Services decide
what "not found" means and shape the response.
"""

from typing import Any, Protocol

Record = dict[str, Any]


class ResearchRepository(Protocol):
    # Workspace and people
    def get_workspace(self, user_id: str) -> Record: ...
    def get_person(self, person_id: str) -> Record | None: ...

    # Projects
    def list_projects(self) -> list[Record]: ...
    def get_project(self, project_id: str) -> Record | None: ...
    def list_project_files(self, project_id: str) -> list[Record]: ...
    def list_conversations(self, project_id: str) -> list[Record]: ...
    def list_instructions(self, project_id: str) -> list[Record]: ...
    def list_memory_items(self, project_id: str) -> list[Record]: ...
    def list_tasks(self, project_id: str) -> list[Record]: ...
    def get_meeting_draft(self, project_id: str) -> Record | None: ...

    # Experiments
    def list_experiments(self, project_id: str) -> list[Record]: ...
    def get_experiment(self, experiment_id: str) -> Record | None: ...
    def get_analysis(self, experiment_id: str) -> Record | None: ...
    def get_next_step(self, experiment_id: str) -> Record | None: ...
    def get_note_draft(self, experiment_id: str) -> Record | None: ...
    def list_uploads(self, experiment_id: str) -> list[Record]: ...

    # Catalog
    def list_evidence_types(self) -> list[Record]: ...
    def list_apps(self) -> list[Record]: ...
    def get_voice_commands(self) -> dict[str, str]: ...

    # Data provenance (e.g. data_mode = SIMULATED)
    def get_meta(self) -> Record: ...
